v0.1.0
cjohnhanson/schematic pull request #1
Opened 2019-05-24 18:54 UTC by cjohnhanson

2019-05-24 21:38 UTC, zar1 reviewed
Made a few comments, then had to catch train. I'll finish the review later

2019-05-24 21:38 UTC, zar1 commented on schematic/base.py
> +    if A is less restrictive than B, then A < B evaluates to True.
Certainly up for debate, but for me this actually makes more sense the other way. I would interpret `A < B` to mean `A ⊂ B`, which means that type B is a larger set of valid options than type A, which means B is less restrictive.

2019-05-24 21:38 UTC, zar1 commented on schematic/base.py
> +    in B and vice versa, A > B, A < B, and A == B all evaluate to False.
Again, debatable, but I think raising an exception might actually be better. The fundamental issue is that we're comparing things that are incomparable. Even if `<`, `>`, and `==` evaluate to false, it still implies that we can talk about a relationship

2019-05-28 15:23 UTC, zar1 requested changes
Saving my work. Not finished yet

2019-05-28 15:23 UTC, zar1 commented on schematic/base.py
> +        if isinstance(
I might implement this by checking that `isinstance(other, type(self)) and self.parameter == other.parameter` rather than depending on names to be the same, esp. since there's no logic here enforcing what the name attribute has to be

2019-05-28 15:23 UTC, zar1 commented on schematic/base.py
> +                return True
I believe by your logic `VARCHAR(1) == VARCHAR(2)`. I would argue that `VARCHAR(1)` should actually be unequal and more restrictive than `VARCHAR(2)`

2019-05-28 15:23 UTC, zar1 commented on schematic/base.py
> +    def is_value_compatible_with_instance(self, value):
We can discuss, but this feels to me like a weird way to use instantiation. I don't want to compare instances and classes against each other; I think that ultimately, we should assume that every  object we're dealing with should be an instance of TableColumnType whether or not the type has an implicit parameter. Said another way, there should only be one `is_value_compatible_with` method rather than two

2019-05-28 15:23 UTC, zar1 commented on schematic/base.py
> +class TableColumnType(NameSqlMixin, DictableMixin, object):
Not sure if you care about py2 compatibility, but in py3 we don't need to subclass `object` any more

2019-05-28 15:23 UTC, zar1 commented on schematic/base.py
> +class TableColumnType(NameSqlMixin, DictableMixin, object):
Also on at least line 168, 184

2019-05-28 15:23 UTC, zar1 commented on schematic/base.py
> +            if col.name == column.name:
```suggestion
            if col.name.upper() == column.name.upper():
```
Not relevant for every dbms, but maybe worth putting here to be safe

2019-05-28 15:23 UTC, zar1 commented on schematic/base.py
> +        """Get the distance between the givenx TableColumnType
```suggestion
        """Get the distance between the given TableColumnType
```

2019-05-28 15:23 UTC, zar1 commented on schematic/base.py
> +        for ct in self.most_restrictive_types:
since we seem to be writing this loop a lot, maybe define an iterator on TableColumnType so we can do stuff like:
```
for dist, nlr in enumerate(leaf_type.most_to_least_restrictive()):
    if nlr == column_type:
        distances.append(dist)
        break
```

2019-05-28 15:23 UTC, zar1 commented on schematic/base.py
> +        return min(distances)
In the event that column_type isn't in the tree anywhere, let's return a special error

2019-05-28 15:23 UTC, zar1 commented on schematic/base.py
> +                if column_type().is_value_compatible_with_class(value):
I'd like to discuss this further, but I think this algorithm might be vulnerable to the following situation. Assume that the least restrictive type is `A` and the most restrictive types are the incompatible types `D` and `F`, as follows:

```
A
|\
B E
| |
C F
|
D
```
Say we have a column with the following two elements:
* `a`, which is compatible with types `D` and `F`
* `b`, which is compatible with type `E`

If we run this algorithm starting with type `a`, then we get:
`get_type(a) -> D`
since `D` is the deepest compatible element, then we run
`get_type(b, D) -> A`, since `A` is the least restrictive type compatible with both `b` and `D`. However, if we order the column in the other direction, we get `E`, which is a better answer:
```
get_type(b) -> E
get_type(a, E) -> E
```
Not sure offhand exactly what the right way to fix this is, but if we have a general framework we probably need to resort to a more exhaustive algorithm

2019-05-28 15:23 UTC, zar1 commented on schematic/base.py
> +        self.parameter = parameter
It would probably be useful to add a `__hash__` method so we could, for example, make a set of all types in the table

2019-05-28 17:00 UTC, zar1 requested changes

2019-05-28 17:00 UTC, zar1 commented on schematic/base.py
> +        already_yielded = []
With `__hash__` and a restrictive type iterator, this could just be:

```
return list(
    frozenset(itertools.chain.from_iterable(
            (leaf.most_to_least_restrictive() for leaf in
             self.most_restrictive_types)))
```
Isn't that just _so_ pythonic?!

2019-05-28 17:00 UTC, zar1 commented on schematic/common.py
> +        return self.name
I think using `psycopg2.sql.Identifier` here might be a good idea. It ensures that identifiers are double-quoted correctly and will probably be fine for other dialects

2019-05-28 17:00 UTC, zar1 commented on schematic/docs/source/conf.py
> +html_theme = 'alabaster'
good choice

2019-05-28 17:00 UTC, zar1 commented on schematic/schematics/redshift_schematic.py
> +TODO(Cody): Determine how/whether to handle CHAR types (currently defaults to VARCHAR)
I can't think of a good reason to convert anything to CHAR, unless we're exporting from another SQL database that's CHAR already

2019-05-28 17:00 UTC, zar1 commented on schematic/schematics/redshift_schematic.py
> +TODO(Cody): Implement how/whether to handle BPCHAR and TEXT types
I wouldn't worry about any of these "alias" text types until we have to, since they're not semantically different

2019-05-28 17:00 UTC, zar1 commented on schematic/schematics/redshift_schematic.py
> +        super(RedshiftTableColumn, self).__init__(name, column_type)
```suggestion
        super().__init__(name, column_type)
```
Unless you're worried about python2

2019-05-28 17:00 UTC, zar1 commented on schematic/schematics/redshift_schematic.py
> +
redshift also keeps track of unique, primary key, and foreign key (although it doesn't enforce them) see https://docs.aws.amazon.com/redshift/latest/dg/t_Defining_constraints.html
Might be worth adding here since it's apparently an optimization hint

2019-05-28 17:00 UTC, zar1 commented on schematic/schematics/redshift_schematic.py
> +    next_less_restrictive = RedshiftVarcharType
I would consider just leaving this out of the tree, since varchar isn't so much a superset of char as it is an optimization

2019-05-28 17:00 UTC, zar1 commented on schematic/schematics/redshift_schematic.py
> +    next_less_restrictive = RedshiftVarcharType
I would argue that the next_less_restrictive type of Boolean is Integer

2019-05-28 17:00 UTC, zar1 commented on schematic/schematics/redshift_schematic.py
> +        return "BOOLEAN".format(self.len)
```suggestion
        return "BOOLEAN"
```

2019-05-28 17:00 UTC, zar1 commented on schematic/base.py
> +    name_regex = None
```suggestion
```
since not every subclass actually implements a regex, I would recommend leaving it out on the superclass

2019-05-28 17:00 UTC, zar1 commented on schematic/base.py
> +class TableColumnType(NameSqlMixin, DictableMixin, object):
It might be worth using the `abc` module for these abstract base classes so we don't accidentally initialize them

2019-05-28 17:00 UTC, zar1 commented on schematic/schematics/redshift_schematic.py
> +        "(^[0-9]{4}-(0[1-9]|1[0-2])-(0[1-9]|1[1-9]|2[1-9]|3[0-1])$)"]
Isn't this just a date rather than a timestamp?

2019-05-28 17:00 UTC, zar1 commented on schematic/schematics/redshift_schematic.py
> +        return "TIMESTAMP".format(self.len)
```suggestion
        return "TIMESTAMP"
```

2019-05-28 17:00 UTC, zar1 commented on schematic/schematics/redshift_schematic.py
> +        "(^[0-9]{4}-(0[1-9]|1[0-2])-(0[1-9]|1[1-9]|2[1-9]|3[0-1])$)"]
isn't this just a date rather than a timestamp?

2019-05-28 17:00 UTC, zar1 commented on schematic/schematics/redshift_schematic.py
> +    next_less_restrictive = RedshiftTimestampType
I think this is backwards. Any string that can be interpreted as a timestamp can be interpreted as a timestamptz, but any timestamptz cannot be a timestamp

2019-05-28 17:00 UTC, zar1 commented on schematic/schematics/redshift_schematic.py
> +    next_less_restrictive = RedshiftTimestampTZType
```suggestion
    next_less_restrictive = RedshiftTimestampType
```
Assuming we agree that TimstampTZ is less restrictive than Timestamp

2019-05-28 17:00 UTC, zar1 commented on schematic/schematics/redshift_schematic.py
> +            float(value)
It's not strictly correct that a decimal can always be converted to a float, but I think this is close enough for now. Let's just add a TODO

2019-05-28 17:00 UTC, zar1 commented on schematic/schematics/redshift_schematic.py
> +    def get_parameter_for_value(value):
factor this out so we're not duplicating `RedshiftAbstractDecimalType.check_compatible`. It's weird enough logic that we definitely don't want to implement it twice

2019-05-28 17:00 UTC, zar1 commented on schematic/schematics/redshift_schematic.py
> +    precision = 15
defining a double as a decimal with limited precision and scale is, at best, a rough approximation. Honestly, I think that numerically, we have two approaches:
* Being really careful about precision, thinking a lot, and implementing a reasonable chain of single -> double -> decimal
* Being lazy and saying it's good enough to just use double for everything more accurate than Integer

I strongly advocate the second approach. It avoids a lot of really tricky math that we probably don't need.

2019-05-28 17:00 UTC, zar1 commented on schematic/schematics/redshift_schematic.py
> +class RedshiftAbstractDecimalType(schematic.TableColumnType):
I made some comments about the implementation of decimal types, but before doing that let's consider whether or not using decimals even makes sense for us. My argument (repeated from below) is:

defining a double as a decimal with limited precision and scale is, at best, a rough approximation. Honestly, I think that numerically, we have two approaches:

* Being really careful about precision, thinking a lot, and implementing a reasonable chain of single -> double -> decimal
* Being lazy and saying it's good enough to just use double for everything more accurate than Integer

I strongly advocate the second approach. It avoids a lot of really tricky math that we probably don't need to worry about.

2019-05-28 17:00 UTC, zar1 commented on schematic/base.py
> +    def __init__(self, parameter=None):
since we're using parameter to represent multiple data types, consider replacing it with `**kwargs` and letting let subclass use whatever variable names it wants

2019-05-28 17:00 UTC, zar1 commented on schematic/schematics/redshift_schematic.py
> +        return (cast_value >= self.min_value and
This can run into issues with numeric imprecision for very large numbers that are close to min_value or max_value. Similar to with decimal numbers, I recommend the lazy approach of just using BIGINT as the only integer type and making this test
```
try:
    int(value)
    return True
except ValueError:
    return False

2019-05-28 17:00 UTC, zar1 commented on schematic/schematics/redshift_schematic.py
> +        self.distkey = None
maybe add `diststyle` as well as distkey. key-based distribution isn't always the correct answer

2019-05-28 17:00 UTC, zar1 commented on schematic/schematics/redshift_schematic.py
> +                self.distkey = col
probably want to raise an error if we encounter more than one distkey

2019-05-28 17:00 UTC, zar1 commented on schematic/schematics/redshift_schematic.py
> +        for sk in sorted(sk_dict.keys()):
optional: list comprehension

2019-06-11 20:15 UTC, cjohnhanson commented on schematic/base.py
> +    if A is less restrictive than B, then A < B evaluates to True.
Agreed, changed.

2019-06-11 20:17 UTC, cjohnhanson commented on schematic/base.py
> +    in B and vice versa, A > B, A < B, and A == B all evaluate to False.
I agree with this in theory, but in practice we'd have to do a full graph traversal for both operands every time we did any comparison. I'll add this as a TODO for a later version.

2019-06-11 20:22 UTC, cjohnhanson commented on schematic/base.py
> +        for ct in self.most_restrictive_types:
Added as a TODO.

2019-06-11 20:23 UTC, cjohnhanson commented on schematic/base.py
> +        self.parameter = parameter
Good idea, added hash methods to the base classes.

2019-06-11 20:24 UTC, cjohnhanson commented on schematic/common.py
> +        return self.name
Good call, all the SQL rendering is now done using psycopg2.sql.SQL objects.

2019-06-11 20:25 UTC, cjohnhanson commented on schematic/schematics/redshift_schematic.py
> +TODO(Cody): Determine how/whether to handle CHAR types (currently defaults to VARCHAR)
True, I mostly added that because in theory I'd like to eventually get this completely 1:1 with Redshift's types, but in practice there's not really a use case for it.

2019-06-11 20:27 UTC, cjohnhanson commented on schematic/schematics/redshift_schematic.py
> +
Added as a TODO for a later version.

2019-06-11 20:30 UTC, cjohnhanson commented on schematic/base.py
> +    name_regex = None
Good call, removed. I added a similar attribute to Redshift types though, so a RedshiftTableDefinition can be instantiated from an actual table in Redshift.

2019-06-11 20:36 UTC, cjohnhanson commented on schematic/schematics/redshift_schematic.py
> +class RedshiftAbstractDecimalType(schematic.TableColumnType):
Agreed, updated to follow the second approach.

2019-06-11 20:37 UTC, cjohnhanson commented on schematic/schematics/redshift_schematic.py
> +    next_less_restrictive = RedshiftVarcharType
Agreed, updated.

2019-06-11 20:42 UTC, cjohnhanson commented on schematic/schematics/redshift_schematic.py
> +        return (cast_value >= self.min_value and
Agreed, updated.

2019-06-11 20:42 UTC, cjohnhanson commented on schematic/schematics/redshift_schematic.py
> +    def get_parameter_for_value(value):
Agreed, updated.

2019-06-11 20:44 UTC, cjohnhanson commented on schematic/schematics/redshift_schematic.py
> +                self.distkey = col
Good call, updated.

2019-06-11 20:47 UTC, cjohnhanson commented on schematic/base.py
> +        return min(distances)
Good call, updated.

2019-06-11 20:54 UTC, cjohnhanson commented on schematic/schematics/redshift_schematic.py
> +    next_less_restrictive = RedshiftTimestampType
Agreed, updated.

2019-06-11 20:56 UTC, cjohnhanson commented on schematic/schematics/redshift_schematic.py
> +            float(value)
Added.

2019-06-11 20:57 UTC, cjohnhanson commented on schematic/base.py
> +    def __init__(self, parameter=None):
I'll add that as a TODO--a lot of the logic here relies on `parameter`.

2019-06-11 21:03 UTC, cjohnhanson commented on schematic/schematics/redshift_schematic.py
> +        self.distkey = None
Added as a TODO for a later version.

2019-06-11 21:05 UTC, cjohnhanson commented
Test output:

```
(schematic) Codys-MacBook-Pro:schematic cody$ytest': pytest --cov=schematic
=========================================================================================== test session starts ============================================================================================
platform darwin -- Python 3.6.2, pytest-4.5.0, py-1.8.0, pluggy-0.11.0
rootdir: /Users/cody/Projects/pipedreams/schematic
plugins: cov-2.7.1
collected 119 items

schematics/tests/test_csv_schematic.py .....                                                                                                                                                         [  4%]
schematics/tests/test_redshift_schematic.py ...........................................................                                                                                              [ 53%]
tests/test_base.py ..................................................                                                                                                                                [ 95%]
tests/test_cli.py .                                                                                                                                                                                  [ 96%]
tests/test_common.py ....                                                                                                                                                                            [100%]

---------- coverage: platform darwin, python 3.6.2-final-0 -----------
Name                               Stmts   Miss  Cover
------------------------------------------------------
__init__.py                            3      0   100%
base.py                              162      9    94%
cli.py                                17      9    47%
common.py                             17      0   100%
schematics/__init__.py                 2      0   100%
schematics/csv_schematic.py           33      0   100%
schematics/redshift_schematic.py     272     17    94%
tests/__init__.py                      0      0   100%
tests/test_base.py                   197      0   100%
tests/test_cli.py                      9      0   100%
tests/test_common.py                  19      0   100%
------------------------------------------------------
TOTAL                                731     35    95%


======================================================================================== 119 passed in 0.60 seconds ========================================================================================
```

2019-06-12 15:25 UTC, zar1 requested changes
This review is for TableColumnType. I'll do the rest in separate reviews

After going through this again, I think the correct inheritance structure uses different abstract base classes for parameterized and unparameterized types, like:

```
TableColumnType
|-ParameterizedTableColumnType
|-UnparameterizedTableColumnType
```

That allows us to clean up a lot of the branches that this class has, including:
* value_is_compatible can be `return self._value_is_compatible_superset` for non-parameterized and can be abstract for parameterized, and then _value_is_compatible_superset can always just be abstract
* get_parameter_for_value doesn't have to be defined at all for non-parameterized

We could save this change for v2, but I think it's easy enough and would sufficiently simplify the code that it's probably worth doing now

2019-06-12 15:25 UTC, zar1 commented on schematic/base.py
> +    name = "TableColumnType"
```suggestion
    @property
    @abstractmethod
    def name(self):
        pass
```
force subclasses to pick their own name

2019-06-12 15:25 UTC, zar1 commented on schematic/base.py
> +    TODO(Cody): Comparisons of incomparable operands should raise an exception
It might make sense to finish this one before the alpha release since it changes the interface

2019-06-12 15:25 UTC, zar1 commented on schematic/base.py
> +    TODO(Cody): Change the "parameter" attribute to use **kwargs.
Since the only parameter we're using so far is varchar length, which is a single integer, I think we're fine with leaving this as a TODO. We can switch to using kwargs in a backwards-compatible way

2019-06-12 15:25 UTC, zar1 commented on schematic/base.py
> +        return hash((self.name, self.parameter))
Probably fine for now, but to be perfectly correct we'll need to guarantee that you can't make more than one TableColumnType with the same name

2019-06-12 15:25 UTC, zar1 commented on schematic/base.py
> +        return isinstance(
optional: I think that `__hash__` should be defined so we can implement this as `return hash(self) == hash(other)`, which is pretty neat

2019-06-12 15:25 UTC, zar1 commented on schematic/base.py
> +            raise NotImplementedError
```suggestion
            return self._value_is_compatible_exactly(value)
```
I think it makes more sense to have functions that are either fully implemented or fully not implemented, so let's pass this to an abstract function either way

2019-06-12 15:25 UTC, zar1 commented on schematic/base.py
> +    def _value_is_compatible_superset(self, value):
```suggestion
    @abstractmethod
    def _value_is_compatible_superset(self, value):
```
Force subclass to define this

2019-06-12 15:25 UTC, zar1 commented on schematic/base.py
> +
```
    @abstractmethod
    def _value_is_compatible_exactly(self, value):
        pass
```
We could debate whether this should be abstract or it should default to: `return self._value_is_compatible_superset(value)`. I favor making it abstract so subclasses have to be more explicit about what they're doing, but I'll leave the final call to you

2019-06-12 15:25 UTC, zar1 commented on schematic/base.py
> +    def get_parameter_for_value(value):
```suggestion
    @abstractmethod
    def get_parameter_for_value(value):
```

2019-06-12 16:28 UTC, zar1 requested changes
Sorry to give you all these new requests. You can decide what you do and don't want to include for a first release

2019-06-12 16:28 UTC, zar1 commented on schematic/base.py
> +        return "{}: {}".format(self.name, self.column_type)
```suggestion
        return "TableColumn('{}', {})".format(self.name, repr(self.column_type))
```
repr should return valid-ish python code. If you want a pretty-print use __str__

2019-06-12 16:28 UTC, zar1 commented on schematic/base.py
> +            return "{} ({})".format(self.name, self.parameter)
```suggestion
            return "{}({})".format(type(self), self.parameter)
```
should be valid-ish python code since this is repr rather than str

2019-06-12 16:28 UTC, zar1 commented on schematic/base.py
> +            return self.name
```suggestion
            return '{}'.format(type(self))
```

2019-06-12 16:28 UTC, zar1 commented on schematic/base.py
> +    def __init__(self, name, columns):
For v2, consider using `*args` instead of `columns`

2019-06-12 16:28 UTC, zar1 commented on schematic/base.py
> +    def create_sql(self):
```suggestion
    @abstractmethod
    def create_sql(self):
```

2019-06-12 16:28 UTC, zar1 commented on schematic/base.py
> +    def __repr__(self):
should return valid-ish python code for creating the object

2019-06-12 16:28 UTC, zar1 commented on schematic/base.py
> +    def create_table(self, *args, **kwargs):
```suggestion
    @abstractmethod
    def create_table(self, *args, **kwargs):
```

2019-06-12 16:28 UTC, zar1 commented on schematic/base.py
> +            if col.name == column.name:
```suggestion
            if col.name.upper() == column.name.upper():
```
to be consistent with above equality logic

2019-06-12 16:28 UTC, zar1 commented on schematic/base.py
> +    def __init__(self, name, columns):
This should make sure none of the columns passed in have the same names

2019-06-12 16:28 UTC, zar1 commented on schematic/base.py
> +        self.name = name
```suggestion
        self.name = name.upper()
```
since columns are treated as type-insensitive in TableDefinition, we might as well nip this in the bud and not worry as much about case in TableDefinition

2019-06-12 16:28 UTC, zar1 commented on schematic/base.py
> +            if col.name == column.name:
If you take my earlier advice and just store column.name in uppercase, disregard

2019-06-12 16:28 UTC, zar1 commented on schematic/base.py
> +    def get_rows(self, *args, **kwargs):
```suggestion
    @abstractmethod
    def get_rows(self, *args, **kwargs):
```

2019-06-12 16:28 UTC, zar1 commented on schematic/base.py
> +    @classmethod
```suggestion
    @classmethod
    @abstractmethod
```

2019-06-12 16:28 UTC, zar1 commented on schematic/base.py
> +    name = 'schematic'
As on line 55, I would make these all
```
@property
@abstractmethod
def prop(self):
    pass
```

to force subclasses to define them

2019-06-12 16:28 UTC, zar1 commented on schematic/base.py
> +                if column_type()._value_is_compatible_superset(value):
```suggestion
                if column_type().value_is_compatible_superset(value):
```
Make this method public if we're calling it from here

2019-06-12 16:28 UTC, zar1 commented on schematic/base.py
> +    def column_type_from_name(self, name):
```suggestion
    @abstractmethod
    def column_type_from_name(self, name):
```

2019-06-12 16:28 UTC, zar1 commented on schematic/cli.py
> +@click.option("--conn-string", help="psycopg2-style connection string")
For v2, a dry_run would be useful here where it just prints the schema

2019-06-12 16:28 UTC, zar1 commented on schematic/schematics/redshift_schematic.py
> +    def_regex = re.compile(r"character varying\(([0-9]+)\)")
For v2, include other aliases like `VARCHAR` and `TEXT`. Also `VARCHAR(MAX)` is a valid type, oh, and there can be whitespace before the `(` I think

2019-06-12 16:28 UTC, zar1 commented on schematic/schematics/redshift_schematic.py
> +    valid_regex = None
inherit ABC, make this an abstract property

2019-06-12 16:28 UTC, zar1 commented on schematic/schematics/redshift_schematic.py
> +    # TODO: BOOL -> BIGINT -> DOUBLE -> VARCHAR
```suggestion
```
I believe you did this already

2019-06-28 16:25 UTC, cjohnhanson commented
For v0.1.0, I'm going to leave out explicitly making the base class methods `@abstractmethod` or properties--it actually breaks a few things that would be pretty onerous to rewrite. I'm also going to leave the parameterization how it is for v0.1.0--changing that would also require a pretty significant rewrite and I think we can bring in the `**kwargs` support for new implementations of `TableColumnType` in a backwards-compatible way. I've added issues for the outstanding changes requested and I'll work them in to the next release.

2019-06-28 16:25 UTC, merged